config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  # resources :categories
  # resources :items
  get 'project/index'

  devise_for :users,path: '',path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'quotation' ,to: 'quotation#quotation'
  get 'site/index'

  # root to:'site#index'
  # root :to => redirect("/login")
  get 'site/ps1'
  get 'site/zero_division_error'
  get 'site/news_page'




  # root 'quotation#quotation'
  get 'quotation', to:'quotation#quotation'
  get 'index', to:'quotation#index'
  get 'export',to: 'quotation#export'
  post 'uploadFile', to:'quotation#uploadFile'
  # get 'about' ,to: 'articles#about'
  post '/quotation', to:'quotation#quotation'
  post 'quotation/quotation'
  get 'sql',to: 'quotation#sql'
  get 'sql1',to: 'quotation#sql1'
  get 'quotation/ps2'

  get 'document',to:'quotation#Document'
  get 'ps4',to:'quotation#ps4'


  # root "project#index" do

  # end
  root "categories#index"
  resources :categories do
    resources :items
    end
  # resources :items do
  #   resources :categories
  # end

end

app/models/quotation.rb
class Quotation < ApplicationRecord
  validates :author_name,presence: true,length: {minimum: 3,maximum: 50}
  validates :quote , presence: true,length: {minimum: 10,maximum: 300}


  def self.search(search)
    if search
      where(["quote LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/controllers/quotation_controller.rb
class QuotationController < ApplicationController
  def quotation
    # @quotations=Quotation.all
    # @category=Quotation.pluck(:category).uniq
    #debugger
    # @quotation=Quotation.where(["quote LIKE ?","%#{params[:search]}%"])
    # @quotation=Quotation.search(params[:search])
    if params[:quotation]
      @quotation = Quotation.new( quotation_params )
      # debugger
      if params[:quotation][:category2]==""
        @quotation.category=params[:quotation][:category]
      else
        @quotation.category=params[:quotation][:category2]
      end
      if @quotation.save
        flash[:notice] = 'Quotation was successfully created.'
        @quotation = Quotation.new
      end
    else
      @quotation = Quotation.new
    end
    if params[:sort_by] == "date"
      @quotations = Quotation.order(:created_at)
    else
      @quotations = Quotation.order(:category)
    end
  end

  def index
    @quotation=Quotation.search(params[:search].downcase)
  end
  def export
    @quotationS=Quotation.all
    # debugger
    # respond_to do |format|
    #   format.xml{render xml: @quotation}
    # end
    # render :xml=>@quotation.to_xml
    # debugger
    render xml: @quotationS
  end
  # def export
  #   @quotation = Quotation.all
  #   respond_to do |format|
  #     # format.html
  #     # # format.js
  #     format.xml { render xml: @quotation }
  #   end
  # end
def uploadFile
  # debugger
  filename =
  xml = File.open("myfile.xml")
  data = Hash.from_xml(xml)
    debugger
end
  def sql
    c=Rails.root.join 'public/basic.txt'
    str=c.to_s
    # debugger
    @file=File.read(str)

  end
  def sql1
    c=Rails.root.join 'public/sample-data.txt'
    str=c.to_s
    # debugger
    @file=File.read(str)

  end
  def Document

  end
  def ps2

    end
  def ps4

  end

  private
  def quotation_params
    params.require(:quotation).permit(:author_name,:category, :quote)
  end
end

app/views/quotation/Document.html.erb
<div class="ui container">
<html>
<head>
  <title></title>
</head>
<body>
<h3>1.What will people be able to learn about in the community that you’re building? Alternatively, if you are automating some collaborative workflow, what work will people accomplish with your system?</h3>

<p>In my system which i am going to build will be helpful for students.Many students likes to have some coffee or sandwich with in the break,but when we go to timeout caffe i takes 10 mins to prepare a sandwich or a coffee.So my application help to the students who can have a coffee or sandwich with in the time by booking the coffee at the particular time from my application.Like i will book a coffee from the class and mention the time that i will come their with in that time to have coffee.</p>
<hr>

<h3>2.What do you want people to say about your service after a visit?</h3>

<p>By honestly saying that we will provide quality products and we will improve our application as per the user comfortable requirements.We give every update as a notification to users.We will work for students to get a positive feedback and we are hopeful that people will feel that our product really helped students.</p>
<hr>
<h3>3.What are the relevant distinct user classes?</h3>

<ol>Based on privileges,my application has three user classes:</ol>
<li>Administrators/Vender(Shopkeeper ):They have complete access to the application.They can also control the whole users with their functionalities. He/she is the person who can add their items in their shop and they edit the items,item details in the application.They can see how many bookings done per day/per month and they can see floating of bookings. </li>
<li> Visitors: They can see the main page of the application. They register and login to be a member of application.</li>
<li>End Users/Customers:They are signed-in users.They can have a booking with their liked items and they can upload a pic what they had.</li>
<hr>
<h3>4.What should a user on a smartphone be able to do?</h3>

<p>The users can do all the things that they are going to do in web application.MAy be we in future if the idea went good in many students heads we will plan to do a mobile application.<p>

<hr>
<h3>5.User Profiles</h3>
<div class="ui link cards">

  <div class="card">
    <div class="image">
<!--      <img src="/images/avatar2/m.jpg">-->
<!--      <img src="/images/avatar2/m.jpg" alt="rss feed" />-->
      <%= image_tag("avatar2/m.jpg") %>
    </div>
    <div class="content">
      <div class="header">Mahesh</div>
      <div class="meta">
        <p>Master student</p>
        <p>Age 22</p>
      </div>
      <div class="description">
        <p>
          Marital Status: Single</p>
        <p> Housing Situation: Student Dorm</p>
        <p>Income: None
        </p>
      </div>
    </div>
    <div class="extra content">
      <span >
        <p style="font-weight: bold">Short-term goals:</p> She need as coffee with in a time
      </span></div>
    <div class="extra content">
      <span >
        <p>Long-term goals: Not wasting the time in TimeOUT cafe</p>
      </span>
    </div>
  </div>
  <div class="card">

    <div class="image">
<!--      <img src="/images/avatar2/t.jpg">-->
      <%= image_tag("avatar2/t.jpg") %>
    </div>
    <div class="content">
      <div class="header">Kitty</div>
      <div class="meta">
        <span class="date">
           <p>PG student</p>
        <p>Age 24</p>
        </span>
      </div>
      <div class="description">
        <p>
          Marital Status: Single</p>
        <p> Housing Situation: Student Dorm</p>
        <p>Income: None
        </p>
      </div>
    </div>
    <div class="extra content">
    <span >
        <p style="font-weight: bold">Short-term goals:</p>  she doesn't like to wait more time for sandwich

      </span></div>
    <div class="extra content">
      <span >
        <p style="font-weight: bold">Long-term goals:</p> Not wasting the time in TimeOUT cafe
      </span>
    </div>
    </div>
  </div>
<!--  <div class="card">-->
<!--    <div class="image">-->
<!--      <img src="/images/avatar2/h.jpg">-->
      <%#= image_tag("avatar2/h.jpg") %>
<!--    </div>-->
<!--    <div class="content">-->
<!--      <div class="header">Vasu</div>-->
<!--      <div class="meta">-->
<!--        <p>Student</p>-->
<!--        <p>Age 24</p>-->
<!--      </div>-->
<!--      <div class="description">-->
<!--        <p>-->
<!--          Marital Status: Married</p>-->
<!--        <p> Housing Situation: Student Dorm</p>-->
<!--        <p>Income: None-->
<!--        </p>-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class="extra content">-->
<!--        <span >-->
<!--        <p style="font-weight: bold">Short-term goals:</p>-->

<!--      </span></div>-->
<!--    <div class="extra content">-->
<!--      <span>-->
<!--        <p style="font-weight: bold">Long-term goals:</p>-->
<!--      </span>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
<hr>

<h3>6.For each class of user identified in Exercise 1a, produce a textual or graphical usage scenario for how that user will experience your service.</h3>

Visitors:
he/she can visit the website
she/he can see all items and pictures provided in the application
he/she can not book the item .

Administrator:
They have complete access to the application.
They can also control the whole users with their functionalities.
He/she is the person who can add their items in their shop.
they edit the items,item details in the application.
They can update every item in application.
They can see how many bookings done per day/per month.
they can see floating graphs of bookings.

Customer:
They are signed-in users.
They can have a booking with their liked items.
They can upload a pic what they had.
They can provide reviews
<hr>

<h3>7.Offline Alternatives</h3>

<p>There is an alternative that going to TimeOut cafe and we can have an order mouth order as per the rash you may get the cafe/sandwich or which item do you need .but it depends on the rash in that cafe but by using my application, you can see the orders having booked before and you can go their and you fix the time to get that coffee or you like item.</p>
<hr>



<h3>8.Online alternatives</h3>

<p>There is no any application for TimeOutCafe in AIT .So there is no any online alternatives to solve the time waster of waiting to have coffee or any item in a cafe.I think my application may fix the problem with showing the latest orders that their are before we order and we can fix the time to have a coffee or any items which the TIMEOUT CAFE provides. </p>
<hr>
<h3>9.Magnet Content</h3>

<p>The main magnetic content of my application is the posts posted by the shopkeeper and the customer posts by having the items.We share our original review as a posts in the application and one thing is about saving time. </p>
<hr>
<h3>10.DNS and HOST Name Registration Procedures</h3>

<p>TimeOutAit.com is our main hostname for our application.Now mainly this application for AITans who is facing problem to have snacks during break time,and also the cafe is present in the AIT itself.So for now we would like to host this web application in AIT server.  There are several options for DNS registration, such as BlueHost, GoDaddy, etc. All these domain name registrars provide domain names for purchase. Once our user base has also increased, we could also scale our servers to Amazon, Azure, etc.</p>
<hr>
11.
<h3>12.All social Web applications have users, content, and some kind of user-to-content map. Specify what kind of information each of these areas will have in your application.</h3>

<p>In our Application we have users ,items and admin information and we also have booking information of the customer and our application also contains the pictures of the users if they upload and will have mainly the items pictures and the prices of the particular item. </p> <hr>
<h3>13.SQL injection</h3>
<p>This page lists many query methods and options in ActiveRecord which do not sanitize raw SQL arguments and are not intended to be called with unsafe user input. Careless use of these methods can open up code to SQL Injection exploits. The examples here do not include SQL injection from known CVEs and are not vulnerabilites themselves, only potential misuses of the methods.</p>
<hr>
<h3>14.Sensitive Data Audit</h3>

<p>For this, you need to encrypt data before it’s sent to the database. This is known as application-level encryption. Use storage-level encryption for all data and application-level encryption for sensitive data.There’s a popular gem called attr_encrypted that integrates nicely with Active Record.
  The production database password is not stored anywhere on the server or in the repository. It is set only once during the setup of the production server and this is done by an environment variable.As usually we has devise gem it automatically hash the password and adds salt to it so this also very useful for developers.</p>
<hr>
<ol><h3>15.User Data Model</h3></ol>
<li>first_name(string)</li>
<li>last_name(string)</li>
<li>stID(varchar)</li>
<li>email(string)</li>
<li>username(string)</li>
<li>is_admin(boolean)</li>
<li>pic(string)</li>
<li>Balance(int)</li>
<hr>
<h3>16.User Registration and User Login</h3>
<p>Gerkhin for BDD:</p>
<p>Feature: User</p>
<p>Scenario : A web user visiting our application page should be able to register.</p>

<pre>Given I want to register myself in the application
And I visit the home page
Then I should see the sign up form
When I fill up my details in the form and click on “Register” button
Then I should be directed back to home/login page
And I should see the message “Successfully registered”
When I fill in my credentials in Login form and click on “Login” button
Then I should be redirected to my user page.</pre>

<p>Scenario : An existing user visiting our application page should be able to login.</p>

<pre>Given I am an already registered user.
And I visit the home page
Then I should see the login form
When I fill in my credentials in Login form and click on “Login” button
Then I should be redirected to my user page.</pre>
<hr>
<!--<div class="image">-->
  <!--      <img src="/images/avatar2/m.jpg">-->
  <!--      <img src="/images/avatar2/m.jpg" alt="rss feed" />-->
  <%#= image_tag("avatar2/a.jpg") %>
<!--</div>-->
<div class="ui full bordered image">
  <!--      <img src="/images/avatar2/m.jpg">-->
  <!--      <img src="/images/avatar2/m.jpg" alt="rss feed" />-->
  <h2>Work Management flow</h2>
  <h3>LogIn</h3>
  <%= image_tag("avatar2/a.png") %>
  <h3>SignUp</h3>
  <%= image_tag("avatar2/b.png") %>
  <h3>Edit profile</h3>
  <%= image_tag("avatar2/d.png") %>
  <h3>Working profile</h3>
  <%= image_tag("avatar2/c.png") %>
</div>

</body>
</html>
</div>

app/views/quotation/export.html.erb
<h1>Hey this is mahesh</h1>

app/views/quotation/index.html.erb
<%= form_tag index_path,:method=>'get' do %>

  Quote <%= text_field_tag :search,params[:search] %>
  <%= submit_tag 'Search' %>
<% end %>
<hr/>
<h3>Quotations</h3>
<ul>
  <% for quotation in @quotation %>
    <li><%= h quotation.author_name %>: <%= h quotation.quote %></li>
  <% end %>
</ul>
<br/>
<%= link_to 'back',quotation_path %>

app/views/quotation/ps2.html.erb
<div class="ui container">
<table>
<tr >
  <td ><h3><%= link_to "Problem Set2",quotation_path %></h3></td>
  <td >
    <ol><li><h4><%= link_to "PS2",quotation_path %></h4></li><br/>
      <h4><li><%= link_to "SQL", sql_path %></li></h4>
      <h4><li><%= link_to "Sample-data", sql1_path %></li></h4></ol></td>
  <td >
    <h4><ol>
      <li>Created a Quotaions and added a drop down box to it .importing Database into Xml file and by uploading a xml file it added to Data base</li>
      <!--        <li>Inthe Secound one i we did all about scraping the data from the AIT main website(ait.ac.th).We brought the titles,pics and given the links to the pics too.</li>-->
    </ol></h4>
  </td>
</tr>
</table>
</div>

app/views/quotation/ps4.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<div class="ui container">
<div class="ui column">
  <h3>
    1)Design your content data model and discuss the implications of your design choices with potential
    users of the system. In general, there should be at least one category of user-submitted content with
    authoring workflow specific to your project and at least one question and answer forum. However,
    the specifics will be very dependent on your project’s requirements. Document the design and your
    discussions on your site.
  </h3>
  <%= image_tag("avatar2/ps4.jpg") %>
</div>
  <h1>2)WorkFlow from both admin and user with their data models.</h1>
  <h1>Users:-</h1>
  <p>Users are the customers who are registered to the site.they can visit the site and they can book the items like coffee and sandwich.In users we also have admin who can ban the users and can added the items and categories to the application.</p>

  <pre>The data model for User is :-

user_id: integer,
user_email: string,
encrypted_password: string,
user_first_name: string,
user_ last_name: string,
user_stID: string,
balance: integer,
admin: boolean,
phone_number: string,
country: string</pre><hr>

  <h1>Category</h1>
  <p>Category is one of the things in my project.Only the admin can add the category into the application only he can edit the category and delete it.Every added category that added by the admin users can see in the form of  pictures.</p>

  <pre>The data model for Category:-

Category_id:integer,
Category_name:string</pre>

  <h1>Items</h1>

  <p>Items is another thing in my application only after selecting category we can see the items belongs to that category.Only the Admin can add the items into the application by selecting the category.The added items every user can see them.They can click into that item in application to book the item or it added to cart.</p>

  <pre>The data model for Item:-

Item_id: integer,
item_name: string,
item_description: text,
category_id: integer,
price: float</pre><hr>

  <h1>Booking</h1>

  <p>Booking has the booking details of the user and the item and the quantity of the items and it also contains the price of the item.Next while the customer booking the item the user must login to the application.</p>

  <pre>The data Model for Booking:-
Booking_id:integer,
Item_id:integer
Quantity:integer
Total_price:float
expected_item:TimeStamp
Is_ready:boolean
Is_paid:boolean</pre><hr>

  <h1>Post</h1>
  <p>Next is posts in my application.every customer who had registered in my application can post a picture while having coffee or sandwich.But it is possible when a user login to appliaction.Post contains description and contains the users id who posted the post.</p>

  <pre>The data Model for Post :-

post_id: integer,
post_description: text,
user_id: integer, </pre><hr>
<h1>
  3)Content Versioning System

</h1>
  <h3>

    Items,categories and Post will be the only content will be versioning system of some kind,due to the
    need of the users the functionalities will be increase.
    <br>The web application maintains  the
    Booking history.<br><br><br>The main content could have versioning are the needs of the statistics of how many users are visiting the cafe per day and the comments in the post like instagram .<br><br><br>Another content versioning is like to track the Orders of the cafe while the customers are booking a item.One more and last functional versioning is while a user likes the post another user should reload the page so i will come out that problem using a ActionCables
  </h3>

<hr>
  <h1>4).User Registration and User Login</h1>
  <p>Gerkhin for BDD:</p>
  <p>Feature: User</p>
  <p>Scenario : A web user visiting our application page should be able to register.</p>

  <pre>Given I want to register myself in the application
And I visit the home page
Then I should see the sign up form
When I fill up my details in the form and click on “Register” button
Then I should be directed back to home/login page
And I should see the message “Successfully registered”
When I fill in my credentials in Login form and click on “Login” button
Then I should be redirected to my user page.</pre>

  <p>Scenario : An existing user visiting our application page should be able to login.</p>

  <pre>Given I am an already registered user.
And I visit the home page
Then I should see the login form
When I fill in my credentials in Login form and click on “Login” button
Then I should be redirected to my user page.</pre>
  <hr>



</div>

</body>
</html>

app/views/quotation/quotation.html.erb
<%#= form_tag quotation_path,:method=>'get' do %>

<!--  Quote <%#= text_field_tag :search,params[:search] %>-->
  <%#= submit_tag 'Search' %>
<%# end %>
<div class="ui container">
<%= form_tag index_path,:method=>'get' do %>

  Quote <%= text_field_tag :search,params[:search] %>
  <%= submit_tag 'Search' %>
<% end %>
<hr/><br/>

<fieldset>
  <legend>File Upload</legend>
<%= form_tag uploadFile_path ,:multipart => true do %>
  <p><label for="upload_file">Select File</label>
    <%= file_field 'upload', 'datafile' %></p>
  <%= submit_tag "Upload" %>
<% end %>
</fieldset>
<br/>
<hr/>
<%= link_to "export XML",export_path%>
<hr/>
<fieldset>
<legend><h3>Quotations</h3></legend>
<ul>
  <% for quotation in @quotations %>
    <li><%= h quotation.author_name %>: <%= h quotation.quote %></li>
  <% end %>
</ul>
<br/>
<% if params[:sort_by] == "date" %>
  <%= link_to "Sort by category", :action => :quotation, :sort_by => :category %>
<% else %>
  <%= link_to "Sort by date", :action => :quotation, :sort_by => :date %>
<% end %>
</fieldset>
<hr/>
<h3>New quotation</h3>
<%#= form_for @quotation, :url => { :action => :quotation } do |form| %>
<%= form_with(model:@quotation , local: true, :url => { :action => :quotation }) do |form| %>
  <%#if @quotation.errors.any? %>
    <% @quotation.errors.full_messages.each do |message| %>
      <%= message %>
      <%end %>
    <%#end %>
  <fieldset>
    <legend>Enter details</legend>
    <div class="form_row">
      <%= form.label :author_name %>
      <%= form.text_field :author_name, :size => 20, :maxlength => 40 %>
    </div>
    <div class="form_row">
      <%= form.label :"New Category" %>
      <%= form.select :category2, Quotation.pluck(:category).uniq,include_blank: true %>
    </div>
    <div class="form_row">
      <%= form.label :category %>
      <%= form.text_field :category, :size => 20, :maxlength => 40 %>
    </div>
<!--    <div class="form_row">-->
      <%#= form.label :"New Category" %>
      <%#= form.select :category, Quotation.pluck(:category).uniq,include_blank: true %>
<!--    </div>-->
    <div class="form_row">
      <%= form.label :quote %>
      <%= form.text_area :quote, :rows => 2, :cols => 40, :maxlength => 500 %>
    </div>
  </fieldset>
  <p>
  <div class="form_row">
    <%= form.submit 'Create' %>
  </div>
  </p>
  <% end %></div>

app/views/quotation/sql.html.erb
<%#= File.read("/ps2ps2/app/public/basic.txt") %>
<% @file.split(/\n/).each do |line| %>
  <pre><%= line %></pre>
<% end %>

app/views/quotation/sql1.html.erb
<%#= File.read("/ps2ps2/app/public/basic.txt") %>
<% @file.split(/\n/).each do |line| %>
  <pre><%= line %></pre>
<% end %>