config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  # resources :categories
  # resources :items
  get 'project/index'

  devise_for :users,path: '',path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'quotation' ,to: 'quotation#quotation'
  get 'site/index'

  # root to:'site#index'
  # root :to => redirect("/login")
  get 'site/ps1'
  get 'site/zero_division_error'
  get 'site/news_page'




  # root 'quotation#quotation'
  get 'quotation', to:'quotation#quotation'
  get 'index', to:'quotation#index'
  get 'export',to: 'quotation#export'
  post 'uploadFile', to:'quotation#uploadFile'
  # get 'about' ,to: 'articles#about'
  post '/quotation', to:'quotation#quotation'
  post 'quotation/quotation'
  get 'sql',to: 'quotation#sql'
  get 'sql1',to: 'quotation#sql1'
  get 'quotation/ps2'

  get 'document',to:'quotation#Document'
  get 'ps4',to:'quotation#ps4'


  # root "project#index" do

  # end
  root "categories#index"
  resources :categories do
    resources :items
    end
  # resources :items do
  #   resources :categories
  # end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
  def show

  end
  def ps1

  end

  def zero_division_error
    begin
      a=1/0
    rescue ZeroDivisionError=>e
      # logger = RAILS_DEFAULT_LOGGER
      # logger.info 'some info'
      # logger.error 'some error'
      logger.error ([e.message])
      @error_message=e.backtrace
    end
  end
  def news_page

    url="https://www.ait.ac.th/"
    unparsed_page=HTTParty.get(url) #to get Raw HTML Page
    parsed_page=Nokogiri::HTML(unparsed_page)
    listings=parsed_page.css(".row-condensed").css("article.grid.col-md-4.blog-list")
    a1=[]
    listings.each do |listing|
      dict={
          "heading"=>listing.css("h3").text,
          "url"=>listing.css("a")[0].attributes["href"].value,
          "src"=>listing.css("img")[0].attributes["src"].value

      }
      a1.push(dict)

    end
    @result= a1
  end
end

app/views/site/index.html.erb
<div class="ui container">
<h1>Web Applications</h1>

<table >
  <tr>
    <th>Assignment</th>
    <th>Links To shown</th>
    <th>Description</th>
  </tr>
  <tr >
    <td ><h3><%= link_to "Problem Set1",'site/ps1' %></h3></td>
    <td >
      <ol><li><h4><%= link_to "Something divided by Zero",'site/zero_division_error' %></h4></li><br/>
        <h4><li><%= link_to "Getting Data from AIT Main Page",site_news_page_path %></li></h4></ol></td>
    <td >
      <h4><ol>
        <li>In the First one i divided the number by the zero and i catch the error and displayed in new View</li>
        <li>Inthe Secound one i we did all about scraping the data from the AIT main website(ait.ac.th).We brought the titles,pics and given the links to the pics too.</li>
      </ol></h4>
    </td>
  </tr>
  <tr >
    <td ><h3><%= link_to "Problem Set2",quotation_path %></h3></td>
    <td >
      <ol><li><h4><%= link_to "PS2",quotation_path %></h4></li><br/>
        <h4><li><%= link_to "SQL", sql_path %></li></h4>
    <h4><li><%= link_to "Sample-data", sql1_path %></li></h4></ol></td>
    <td >
      <h4><ol>
        <li>Created a Quotaions and added a drop down box to it .importing Database into Xml file and by uploading a xml file it added to Data base</li>
<!--        <li>Inthe Secound one i we did all about scraping the data from the AIT main website(ait.ac.th).We brought the titles,pics and given the links to the pics too.</li>-->
      </ol></h4>
    </td>
  </tr>
  <tr>
    <tr>
<!--  <td></td>-->
      <td ><h3><%= link_to "Problem Set3",document_path %></h3></td>
      <td >
          <h4><li><%= link_to "Document", document_path %></li></h4>

  </td><td></td>
  </tr>
  <tr>
    <td>
     <h3> <%=link_to "Problem Set4",ps4_path %></h3>
    </td><td>
      <%=link_to "Additional Document",ps4_path %>
    </td>
    <td></td>
  </tr>

</table>

</div>

app/views/site/news_page.html.erb
<div class="ui container">
<!--<h1>Hey.....!</h1>-->
<%#= raw @result %>
<!--=====================================-->
<%# @result.each do |result| %>
<!--  <table>-->
<%#result.each do |key,value| %>

<!--    <tr>-->
<!--      <td>-->
<%#= key["title"] %>
<!--      </td>-->
<!--    </tr>-->

<%#end %>
<!--  </table>-->
<%# end %>
<table style="text-align: center">

  <% @result.each do |result| %>

    <tr>
      <!--      <%#= result["url"] %>>-->
      <!--      <td><a href=result['url']> <%#= image_tag(result['src'], :alt => "rss feed") %></a></td>-->
      <td><%=link_to image_tag(result['src']), result['url'] %></td>
      <!--      <td><%# result["src"] %></td>-->
      <td><%= link_to "Link",result['url'] %></td>
    </tr>
    <tr>
      <td><h3><%= raw result["heading"] %></h3></td>
    </tr>
  <% end %>

</table>
</div>

app/views/site/ps1.html.erb
<h1>Problem Set -1</h1>

<!--<ol>-->
<!--  <li><%#= link_to "Something divided by Zero",'zero_division_error' %></li>-->
<!--  <li><%#= link_to "Getting Data from AIT Main Page",'news_page' %></li>-->
<!--</ol>-->


<table>
  <tr >
    <td ><h3><%= link_to "Problem Set1",site_ps1_path %></h3></td>
    <td >
      <ol><li><h4><%= link_to "divided by Zero",site_zero_division_error_path %></h4></li><br/>
<!--        <h4><li><%#= link_to "SQL", sql_path %></li></h4>-->
        <h4><li><%= link_to "Data from AIT Main Page", site_news_page_path %></li></h4></ol></td>
    <td >
      <h4><ol>
        <li>In the First one i divided the number by the zero and i catch the error and displayed in new View</li>
        <li>Inthe Secound one i we did all about scraping the data from the AIT main website(ait.ac.th).We brought the titles,pics and given the links to the pics too.</li>
      </ol></h4>
    </td>
  </tr>
</table>

app/views/site/zero_division_error.html.erb
<h1><%= @error_message %></h1>