config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  # resources :categories
  # resources :items
  get 'project/index'

  devise_for :users,path: '',path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'quotation' ,to: 'quotation#quotation'
  get 'site/index'

  # root to:'site#index'
  # root :to => redirect("/login")
  get 'site/ps1'
  get 'site/zero_division_error'
  get 'site/news_page'




  # root 'quotation#quotation'
  get 'quotation', to:'quotation#quotation'
  get 'index', to:'quotation#index'
  get 'export',to: 'quotation#export'
  post 'uploadFile', to:'quotation#uploadFile'
  # get 'about' ,to: 'articles#about'
  post '/quotation', to:'quotation#quotation'
  post 'quotation/quotation'
  get 'sql',to: 'quotation#sql'
  get 'sql1',to: 'quotation#sql1'
  get 'quotation/ps2'

  get 'document',to:'quotation#Document'
  get 'ps4',to:'quotation#ps4'


  # root "project#index" do

  # end
  root "categories#index"
  resources :categories do
    resources :items
    end
  # resources :items do
  #   resources :categories
  # end

end

app/models/post.rb
class Post < ApplicationRecord
# class Post < ActiveRecord::Base
  acts_as_votable
  validates :description, presence: true,length: { minimum: 10 } ,:case_sensitive => false
  validates :image,presence: true

  # acts_as_votable
  belongs_to :user
  has_one_attached :image

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user[:id]
    # debugger
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
    @post=Post.find(params[:id])
    @post.upvote_by current_user
    # redirect_to :back "This is belong to rails.4"
    redirect_back(fallback_location: posts_path)
  end
  def downvote
    @post=Post.find(params[:id])
    @post.downvote_by current_user
    # redirect_to :back
    redirect_back(fallback_location: posts_path)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :user_id, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :image,"Image" %>
    <%= form.file_field :image ,class:"ui button"%>
  </div>
  <div class="field">
    <%#= form.label :user_id %>
    <%= form.hidden_field :user_id %>
    <%#= text_field_tag(Post,value=Post.current_user.first_name,disabled: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>Posts</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Description</th>-->
<!--      <th>User</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @posts.each do |post| %>
<!--      <tr>-->
<!--        <td><%#= post.description %></td>-->
<!--        <td><%#= post.user %></td>-->
<!--        <td><%#= image_tag(post.image) %></td>-->
<!--        <td><%#= link_to 'Show', post %></td>-->
<!--        <td><%#= link_to 'Edit', edit_post_path(post) %></td>-->
<!--        <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<%= link_to 'New Post', new_post_path %>

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body style="background-color: rgba(0,0,0,0.2)">
<div class="ui container">
  <% @posts.each do |post| %>
  <div class="ui centered card">
    <div class="content">
      <div class="right floated meta">14h</div>
      <!--        <img class="ui avatar image" src="/images/avatar/large/elliot.jpg"> Elliot-->
      <% if post.user.image.attached? %>
        <%= image_tag(post.user.image) %>
      <%else %>
        <%# image.tag 'avatar2' %>
        <%= image_tag "avatar2/user_blank_pic.jpg", class: "ui avatar image"%><%= post.user.first_name %>
      <%end %>
    </div>
    <div class="image">
      <!--        <img>-->
      <%= image_tag(post.image, :class=> "ui medium rounded image",style: "height:300px;width:300px")  %>
      <%#= @post.user.first_name %>
    </div>
    <div class="content">
    <span class="right floated">
<!--      <i class="heart outline like icon"></i>-->
      <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
<!--        <span class="glyphicon glyphicon-chevron-down"></span>-->
        <%if user_signed_in? and (post.votes_for_ids).include? current_user[:id] %>
          <i class="heart icon"></i>
          <%else %>
        <i class="heart outline like icon"  onclick="myfunction()"></i>
          <%end %>
        <%#=current_user[:id] %>
<!--        Downvote-->
        <%#= link.get_downvotes.size %>
      <% end %>
      <%= post.get_upvotes.size %> likes
    </span>
      <i class="comment icon"></i>
      3 comments
    </div>
    <div class="content">
      <%= post.description %>
    </div>
    <div class="extra content">
      <div class="ui large transparent left icon input">
        <i class="heart outline icon"></i>
        <input type="text" placeholder="Add Comment...">
      </div>
    </div>
  </div>
    <%end %>
</div>
</body>
<script>
  function myfunction(){
      document.getElementById("demo").style.color = "red";
  }
</script>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<p>-->
<!--  <strong>Description:</strong>-->
  <%#= @post.description %>
<!--</p>-->

<!--<p>-->
<!--  <strong>User:</strong>-->
  <%# if @post.user.image.attached? %>
    <%#= @post.user.image %>
    <%#else %>
      <%# image.tag 'avatar2' %>
    <%#= image_tag "avatar2/user_blank_pic.jpg", class: "ui medium image",style: "height:100%;width:100%" %>
    <%#end %>
<!--</p>-->
<!--<p>-->
  <%#= image_tag(@post.image)%>
<!--</p>-->

<!--<%#= link_to 'Edit', edit_post_path(@post) %> |-->
<%#= link_to 'Back', posts_path %>

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body style="background-color: rgba(0,0,0,0.2)">
  <div class="ui container">
    <div class="ui centered card">
      <div class="content">
        <div class="right floated meta">14h</div>
<!--        <img class="ui avatar image" src="/images/avatar/large/elliot.jpg"> Elliot-->
            <% if @post.user.image.attached? %>
            <%= image_tag(@post.user.image) %>
            <%else %>
            <%# image.tag 'avatar2' %>
            <%= image_tag "avatar2/user_blank_pic.jpg", class: "ui avatar image"%><%= @post.user.first_name %>
            <%end %>
      </div>
      <div class="image">
<!--        <img>-->
        <%= image_tag(@post.image, :class=> "ui medium rounded image",style: "height:100%;width:100%")  %>
        <%#= @post.user.first_name %>
      </div>
      <div class="content">
    <span class="right floated">
      <i class="heart outline like icon"></i>
      17 likes
    </span>
        <i class="comment icon"></i>
        3 comments
      </div>
      <div class="content">
        <%= @post.description %>
      </div>
      <div class="extra content">
        <div class="ui large transparent left icon input">
          <i class="heart outline icon"></i>
          <input type="text" placeholder="Add Comment...">
        </div>
      </div>
    </div>
  </div>
</body>
</html>