config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  # resources :categories
  # resources :items
  get 'project/index'

  devise_for :users,path: '',path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'quotation' ,to: 'quotation#quotation'
  get 'site/index'

  # root to:'site#index'
  # root :to => redirect("/login")
  get 'site/ps1'
  get 'site/zero_division_error'
  get 'site/news_page'




  # root 'quotation#quotation'
  get 'quotation', to:'quotation#quotation'
  get 'index', to:'quotation#index'
  get 'export',to: 'quotation#export'
  post 'uploadFile', to:'quotation#uploadFile'
  # get 'about' ,to: 'articles#about'
  post '/quotation', to:'quotation#quotation'
  post 'quotation/quotation'
  get 'sql',to: 'quotation#sql'
  get 'sql1',to: 'quotation#sql1'
  get 'quotation/ps2'

  get 'document',to:'quotation#Document'
  get 'ps4',to:'quotation#ps4'


  # root "project#index" do

  # end
  root "categories#index"
  resources :categories do
    resources :items
    end
  # resources :items do
  #   resources :categories
  # end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true,uniqueness: true, length: { minimum: 3 } ,:case_sensitive => false

  has_one_attached :image
  # has_one_attached: image

  has_many :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order("id ")
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name,:image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="ui container">
  <div class="ui form">
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :image,"Image" %>
    <%= form.file_field :image ,class:"ui button"%>
  </div>

<!--  <div class="actions">-->
  <div class="field">
    <%= form.submit "Create",class: "ui button"%>
  </div>
<% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%#= link_to 'Back', categories_path %>
<br/>
<%= link_to 'Back', categories_path,class:"large ui button" %>

app/views/categories/index.html.erb
<!--<div class="ui container">-->
<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>Categories</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Name</th>-->
<!--      <th colspan="4"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @categories.each do |category| %>
<!--      <tr>-->
<!--        <td><%#= category.name %></td>-->
<!--        <td>-->
          <%# if category.image.attached? %>
          <%#= image_tag(category.image,:width => 100, :height => 100) %>
          <%#end %>
<!--        </td>-->
<!--        <td><%#= link_to 'Show', category %></td>-->
<!--        <td><%#= link_to 'Edit', edit_category_path(category) %></td>-->
<!--        <td><%#= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<%#= link_to 'New Category', new_category_path %>
<!--</div>-->
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body id="bg">
<div class="ui container fluid" >
  <div class="ui container">
    <h1 style="color:white;font-weight: bold;text-align: center;font-family: 'Courier New';margin-top:10%">Welcome To TimeOut</h1>
    <div class="ui six column grid" id="mahesh">

      <!--    <div class="three wide column">hey</div>-->
      <!--    <div class="three wide column">hello</div>-->
      <!--    <div class="three wide column">this</div>-->
      <!--    <div class="three wide column">is mahesh</div>-->
      <!--    <div class="three wide column">this</div>-->
      <!--    <div class="three wide column">is mahesh</div>-->
      <%# if user_signed_in? && current_user.admin="true" %>
      <% if user_signed_in? && current_user.admin==true %>
        <div class="column" style="height:259.75px;width:192.5px">
          <div class="ui segment" style="height:100%;width:100%">
            <!--      <img>-->
            <%#= link_to new_category_path do %>
            <%= link_to new_category_path do %>
              <%= image_tag "avatar2/category.jpg", class: "ui medium image",style: "height:100%;width:100%" %>
              <div class="middle">
                <div class="text">Add New Categories</div>
              </div>
            <% end %>
          </div>
        </div>
      <%end %>



      <% @categories.each do |category| %>
        <div class="column" style="height:259.75px;width:192.5px" >
          <div class="ui segment" style="height:100%;width:100%">
            <!--      <img>-->
            <%#= link_to category do %>
            <%= link_to category_items_path(category) do %>
              <%#= image_tag(@category.image) %>
              <%#= image_tag(category.image, :class=> "ui medium image",style: "height:100%;width:100%")  %>
              <% if category.image.attached? %>
                <%= image_tag(category.image, :class=> "ui medium rounded image",style: "height:100%;width:100%")  %>
              <%else %>
                <%= image_tag "avatar2/coming_soon.jpg", class: "ui medium image",style: "height:100%;width:100%" %>
              <%end %>
              <div class="middle">
                <div class="text">Visit <%= category.name %></div>
              </div>
            <% end %>
          </div>

        </div>
      <%end %>



      <%# if user_signed_in? and current_user.admin==true %>
<!--        <div class="column" style="height:259.75px;width:192.5px">-->
<!--          <div class="ui segment" style="height:100%;width:100%">-->
            <!--      <img>-->
            <%#= link_to root_path do %>
              <%#= image_tag "avatar2/new_items.jpg", class: "ui medium image",style: "height:100%;width:100%" %>
<!--              <div class="middle">-->
<!--                <div class="text">Add New Items</div>-->
<!--              </div>-->
            <%# end %>
<!--          </div>-->
<!--        </div>-->
      <%#end %>
      <!--    <div class="column">hey1</div>-->
      <!--    <div class="column">hey2</div>-->
      <!--    <div class="column"></div>-->
      <!--    <div class="column"></div>-->
      <!--    <div class="column"></div>-->
      <!--    <div class="column"></div>-->
    </div>
  </div>
</div>
</body>
</html>

app/views/categories/new.html.erb
<div class="ui container">
<h1>New Category</h1>

<%= render 'form', category: @category %>
<br/>
<%= link_to 'Back', categories_path,class:"large ui button" %>
</div>

app/views/categories/show.html.erb
<!--<div class="ui container">-->
<!--  <div class="ui placeholder segment">-->
<!--    <div class="ui two column very relaxed stackable grid">-->
<!--      <p id="notice"><%#= notice %></p>-->
<!--      <div class="column">-->


<!--          <p>-->
          <%#= image_tag(@category.image,:width => 100, :height => 100) %>

<!--          </p>-->

<!--          <%#= link_to 'Edit', edit_category_path(@category) %> |-->
          <%#= link_to 'Back', categories_path %>
<!--      </div>-->
<!--      <div class=" column">-->
<!--        <div class="ui card">-->
<!--          <div class="card">-->
<!--            <div class="content">-->
<!--              <div class="header"><%#= @category.name %></div>-->
<!--              <div class="meta">Friend</div>-->
<!--              <div class="description">-->
<!--                Elliot Fu is a film-maker from New York.-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--        <strong>Name:</strong>-->
        <%#= @category.name %>
<!--      </div>-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class="ui vertical divider">-->
<!--      Or-->
<!--    </div>-->
<!--  </div>-->

<!--</div>-->
<div class="ui container">
<div class="ui segment">
  <div class="ui two column very relaxed grid">
    <div class="medium aligned column">
<!--      <p></p>-->
<!--      <p></p>-->
<!--      <p></p>-->
<!--      <p></p>-->
      <div class="ui large bordered image">
      <%#= image_tag(@category.image) %>
        <% if @category.image.attached? %>
          <%= image_tag(@category.image, :class=> "ui medium rounded image",style: "height:100%;width:100%")  %>
        <%else %>
          <%= image_tag "avatar2/coming_soon.jpg", class: "ui medium image",style: "height:100%;width:100%" %>
        <%end %>
      </div>
      <!--          </p>-->
<!--<p>-->
<!--      <%#= link_to 'Edit', edit_category_path(@category) %> |-->
<!--      <%#= link_to 'Back', categories_path %></p>-->
    </div>
    <div class="column">
<!--      <p></p>-->
<!--      <p></p>-->
<!--      <p></p>-->
<!--      <p></p>-->
      <div class="ui centered card" style="text-align: center;top:50%;left:50%;transform: translate(-50%, -50%);-ms-transform: translate(-50%, -50%);border: 3px solid skyblue">
<!--        <div class="card">-->
          <div class="content">
            <div class="header"><h1>Category:<%= @category.name %></h1></div>
<!--            <div class="meta">Friend</div>-->
            <% if user_signed_in? && current_user.admin==true %>
            <div class="description">
<!--              Elliot Fu is a film-maker from New York.-->
<!--              <p>-->
<!--                <button class="positive ui button"></button>-->
                <%= link_to 'Edit', edit_category_path(@category),class:"positive ui button" %>
                <%= link_to 'Back', categories_path ,class:"negative ui button"%>
<!--              </p>-->
            </div>
              <%else %>
              <div class="description">
                <%= link_to 'Back', categories_path ,class:"negative ui button"%>
              </div>
              <%end %>
<!--          </div>-->
        </div>
        <!--        <strong>Name:</strong>-->
        <%#= @category.name %>
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Details
  </div>
</div>
</div>